# Generated by Django 5.1.5 on 2025-02-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='tittle',
            new_name='title',
        ),
    ]
