# Generated by Django 5.1.5 on 2025-02-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_tittle_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tittle',
            new_name='title',
        ),
    ]
